### ISSUE TITLE
请问下载了应该怎么用？

### ISSUE THREAD

**Issue by MAGUADIDI** [jvjhfhg/DataStructure#1]
VS2015,这不是一个项目，不能直接打开。新建项目后source文件夹下的头文件和LIB文件夹下的头文件应该放在项目哪里？b_plus_tree文件报了很多错。。不知道是不是我放错位置了

**Comment by jvjhfhg** [comment]
您好，这确实不是一个完整的项目，这是我们的大作业。b_plus_tree确实会报很多warning，应该是我们实现的时候没太注意。
